article/urls.py
from django.contrib import admin
from django.urls import path
from . import views   #Bu klasörde bulunan views'ı al

app_name = "article"

urlpatterns = [path('dashboard/',views.dashboard,name="dashboard"),
               path('addarticle/',views.addArticle,name="addarticle"),
               path("article/<int:id>",views.details,name="detail"),
               path("update/<int:id>",views.updateArticle,name="update"),
               path("delete/<int:id>",views.deleteArticle,name="delete"),
               path("",views.articles,name="articles"),
    
]

dogukan_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views  #Websitesi için oluşturduğumuz fonksiyonları import ediyoruz.
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path("about/",views.about, name="about"),
    path("user/",include("user.urls")),    #Eğer localhost/user/register veya localhost/user/login gibi işlemler istendiği zaman django template otomatik olarak user dosyasındaki urls.py dosyasına gidecek ve user/'ın adresinin devamını orada tamamlayacak.
    path("articles/",include("article.urls")),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="user"

urlpatterns=[
    path("register/",views.register, name="register"),
    path("login/",views.loginUser, name="login"),
    path("logout/",views.logoutUser, name="logout"),
    
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="{% url 'index' %}">Doğukan's Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
      
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about'%}">Hakkımda</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:articles' %}">Makaleler</a>
          </li>
        </ul>

        
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}    <!-- Eğer kullanıcı siteye login yaptıysa alttakiler gözükecek -->
          
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="/user/logout">Çıkış Yap</a>
          </li>
          
          
          {% else %}     <!--Eğer kullanıcı login yapmadıysa -->
          
          <li class="nav-item active">
            <a class="nav-link" href="/user/login">Giriş Yap</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="/user/register">Kayıt Ol</a>
          </li>
          {% endif %}
        
      
        </ul>
        
      </div>
  </nav>