article/urls.py
from django.contrib import admin
from django.urls import path
from . import views   #Bu klasörde bulunan views'ı al

app_name = "article"

urlpatterns = [path('dashboard/',views.dashboard,name="dashboard"),
               path('addarticle/',views.addArticle,name="addarticle"),
               path("article/<int:id>",views.details,name="detail"),
               path("update/<int:id>",views.updateArticle,name="update"),
               path("delete/<int:id>",views.deleteArticle,name="delete"),
               path("",views.articles,name="articles"),
    
]

dogukan_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views  #Websitesi için oluşturduğumuz fonksiyonları import ediyoruz.
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path("about/",views.about, name="about"),
    path("user/",include("user.urls")),    #Eğer localhost/user/register veya localhost/user/login gibi işlemler istendiği zaman django template otomatik olarak user dosyasındaki urls.py dosyasına gidecek ve user/'ın adresinin devamını orada tamamlayacak.
    path("articles/",include("article.urls")),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="user"

urlpatterns=[
    path("register/",views.register, name="register"),
    path("login/",views.loginUser, name="login"),
    path("logout/",views.logoutUser, name="logout"),
    
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):   #Bizim sql veritabanında kullanılacak olan makalelerimizi koyacağımız article tablosu

                                                                                                              #Bu makalenin yazar ismini veritabanında oluşturulan kullanıcı adından alacak, bunu yapabilmek için foreignkey modülüyle oluşturuyoruz
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE,verbose_name = "Yazar")                  #ve auth.User ile kayıtlı olan kullanıcılara ulaşıyoruz. Bununla beraber on_delete fonksiyonu ile eğer kullanıcı hesabını silersek, otomatik olarak o kullanıcının oluşturduğu makaleler de silinecek
    title = models.CharField(max_length=40,verbose_name = "Başlık")
    content = RichTextField(verbose_name="İçerik")                                         #Verbose_name ile content isminin admin panelinde İçerik ismiyle gözükmesini sağlıyoruz
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")  #Makalenin oluşturulduğu tarihe göre otomatik tarih değeri alacak.
    article_image = models.FileField(blank=True,null=True,verbose_name="Makaleye Fotoğraf Ekleyin")

    def __str__(self):
        return self.title    #Artık article objesini print(Article) işlemi yapıldığında veya admin panelinde Article object ile bakıldığı zaman bize makalenin başlığı gözükecek. 


class Comment(models.Model):

    article = models.ForeignKey(Article, on_delete=models.CASCADE,verbose_name="Makale")
    comment_author = models.CharField(max_length=20,verbose_name="İsim")
    comment_content = models.CharField(max_length=200,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):               #Eğer bizim elimizde Article modeli var ve bu form Article modeline göre oluşturulacak.
    class Meta:
        model = Article                           #Burdaki formumuzla Article modelini bağlantılı hale getirdik.
        fields =["title","content","article_image"]               #Article ekleme formumuzda sadece title ve content değerlerini alacağımızı belirttik.

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):  #Fonksiyonların içine http requestlerini(get-post gibi) koymak için requesti her zaman koymamız gerekiyor.
    return render(request,"index.html")


def about(request):
    return render(request,"about.html")


def articles(request):

    keyword = request.GET.get("keyword")                #Eğer arama çubuğuna kelime yazıldıysa ona uygun makale olup olmadığına bakıyor.
    if keyword :
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})


    articles=Article.objects.all()       #Veritabanındaki tüm makaleleri articles'ın içine attık liste halinde
    return render(request,"articles.html",{"articles":articles})




@login_required(login_url = "user:login")  #Eğer kullanıcı girişi yapılmadan bu siteye girilmeye çalışılırsa kullanıcı giriş ekranına yönlendirilecek
def dashboard(request):
    articles = Article.objects.filter(author=request.user)  #Hesapta bulunan kullanıcının yazdığı makaleleri aldık
    context={"articles":articles}
    return render(request,"dashboard.html",context)





#Makale Ekleme işlemi
@login_required(login_url = "user:login")  #Eğer kullanıcı girişi yapılmadan bu siteye girilmeye çalışılırsa kullanıcı giriş ekranına yönlendirilecek
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    
    if form.is_valid():
        article = form.save(commit=False)   #Biz title ve content bilgilerini addarticle sitesinden aldık fakat user bilgisine sahip değiliz bu yüzden veritabanına kaydetmeden önce user'ı biz içine koyup kaydedicez.
        article.author= request.user
        article.save()
        messages.success(request,"Makale başarıyla oluşturuldu!")
        return redirect("index")

    return render(request,"addarticle.html",{"form":form})

@login_required(login_url = "user:login")  #Eğer kullanıcı girişi yapılmadan bu siteye girilmeye çalışılırsa kullanıcı giriş ekranına yönlendirilecek
def updateArticle(request,id):  #Makale Güncelleme İşlemi

    article = get_object_or_404(Article,id=id) #Bize girilen id'deki makalenin bilgilerinin article içine koy fakat eğer belirtilen id'de makale yoksa ve kullanıcı websitede bu sayfayı açmaya çalışırsa 404 hatasını ver.

    form = ArticleForm(request.POST or None,request.FILES or None, instance = article)  #Id'sini belirttiğimiz makalenin bilgilerini formun içine koyduk

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale Başarıyla Güncellendi!")

        return redirect("article:dashboard")
    
    else:
        return render(request,"update.html",{"form":form})


@login_required(login_url = "user:login")  #Eğer kullanıcı girişi yapılmadan bu siteye girilmeye çalışılırsa kullanıcı giriş ekranına yönlendirilecek
def deleteArticle(request,id):

    article = get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Makale Başarıyla Silindi")
    return redirect("article:dashboard")




def details(request,id):   #Makalelerin detay sayfası
    article=get_object_or_404(Article,id=id)  #Bize girilen id'deki makalenin bilgilerinin article içine koy fakat eğer belirtilen id'de makale yoksa ve kullanıcı websitede bu sayfayı açmaya çalışırsa 404 hatasını ver.
    return render(request,"details.html",{"article":article})

templates/about.html
{% extends "layout.html" %}

{% block body %}

<h3>Hakkımızda</h3>
<hr>
<p>Merhaba! Ben Doğukan Kumru.</p>

{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

<div class= "row">
    <div class= "col-md-6 offset-md-3">   <!-- Makale Ekle formumuz artık sayfanın ortasında gözüküyor-->

<h3>Makale Ekle</h3>
<hr>

    <form method ="post" enctype="multipart/form-data" >   <!-- Formlara eklenen resim dosyalarının gözükmesi için enctype="multipart/form-data" ekliyoruz. -->
    {% csrf_token %}   <!-- Güvenlik amacıyla djangonun hata vermesini önlemek için -->

    {{form.media}}   <!-- Ckeditörün kullanılabilmesi için -->
    {{form|crispy}}

    <button type = "submit" class="btn btn-danger">Makale Ekle</button>
    </form>

    </div>
</div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}
<form >
<p align="right"><input type="text" name="keyword" class="input-sm" maxlength="64" placeholder="Ara.."> <button type="submit" class="btn btn-primary">Ara</button></p>

</form>
<div class= "row">
    <div class= "col-md-8 offset-md-3">
<h3>Makaleler</h3>
<hr>




</div>
</div>
<div class= "row">
    <div class= "col-md-10 offset-md-3">
{% if articles %}

{% for article in articles %}

<div class="container mt-5">
            <div class="row">
                <div class="col-lg-7">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <a href="{% url 'article:detail' article.id %}"><h3 class="fw-bolder mb-1">{{article.title}}</h3> </a>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">{{article.created_date}} tarihinde {{article.author.username}} tarafından oluşturuldu</div>
                            <!-- Post categories-->
                            
                        </header>
                        <hr>
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                        <a href="/articles/article/{{article.id}}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
                        <hr>
                        {% endif %}
                        
                        <!-- Post content-->
                        <section class="mb-5">
                            {{article.content|safe|truncatewords:30}}  <!--Ckeditorde yazılaların güzel gözükmesi için safe tagı ekliyoruz -->
                        </section>
                        
                    </article>
                    
                </div>
                
                
            </div>
        
</div>

{% endfor %}

    

{% else %}

<div class="alert alert-danger">Henüz makale bulunmuyor! </div>

{% endif %}


{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Kontrol Paneli</h3>
<hr>
<p> Hoşgeldiniz, {{request.user.username}} </p>
<hr>

<a class="btn btn-danger" href="/articles/addarticle" >Makale Ekle</a>
<hr>
{% if articles %}   <!-- Eğer kullanıcının makalesi bulunuyorsa sırasıyla bu makaleleri ekranda gözükecek-->

<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Oluşturulma Tarihi</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for i in articles  %}
    
    <tr>
      <th scope="row">{{i.id}}</th>
      <td><a href="/articles/article/{{i.id}}">{{i.title}} </a></td>  <!--Makale başlığına dokununca o makale açılacak -->
      <td>{{i.author.username}}</td>
      <td>{{i.created_date}}</td>
      <td><a href="/articles/update/{{i.id}}" class="btn btn-info">Güncelle </a></td>
      <td><a href="/articles/delete/{{i.id}}" class="btn btn-danger">Sil </a></td>
    </tr>
  {% endfor %}
    
  </tbody>
</table>
{% else %}  <!-- Fakat bir makalesi bulunmuyor ise alttaki uyarıyı alacak-->

<div class="alert alert-danger"> Henüz bir makaleniz bulunmuyor </div>

{% endif %}


{% endblock body %}

templates/details.html
{% extends "layout.html" %}

{% block body %}

<div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">{{article.created_date}} tarihinde {{article.author.username}} tarafından oluşturuldu</div>
                            <!-- Post categories-->
                            
                        </header>
                        <hr>
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
                        <hr>
                        {% endif %}
                        
                        <!-- Post content-->
                        <section class="mb-5">
                            {{article.content|safe}}  <!--Ckeditorde yazılaların güzel gözükmesi için safe tagı ekliyoruz -->
                        </section>
                    </article>

                   
                    
                </div>
                
                
            </div>
        </div>

{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}
<div class = "jumbotron text-center">
<h3>Doğukan'ın Bloğuna Hoşgeldiniz..</h3>
<p>Bu blogta yazılımlarınızı paylaşıp insanların kendilerini geliştirmesine olanak sağlayabilirsiniz.</p>
</div>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Dogukan Blog</title>
</head>
<body>
{% include "includes/navbar.html" %}   <!--Sitemizin üst kısmında bulunan navigation barı tüm html dosyalarımıza dahil etmek için layout.html'e include ediyoruz.-->
    

    <div style = "margin-top: 100px; margin-bottom: 100px;"class="container">
    <!-------------------------------------------------------------------------->
    
    {% if messages %}
    {% for message in messages %}                                                            <!-- flash mesajlarının içerildiği bölüm -->

    {% if message.tags == "info" %}
    <div class="alert alert-danger">{{ message }}</div>
    {% else %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endif %}
    {% endfor %}
    {% endif %}
    <!---------------------------------------------------------------------------->
    {% block body %}
    
    {% endblock body %}
    </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}              <!-- Crispy formlarının dahil edilmesi -->

{% block body %}
<div class="row">
    <div class = "col-md-6 offset-md-3">      <!-- Login formumuz artık sayfanın ortasında gözüküyor-->
<h3>Giriş Yap</h3>
<hr>

<form method ="post">
    {% csrf_token %}
    {{form|crispy}}
    <br>
    <button type="submit" class="btn btn-danger">Giriş Yap</button>
</form>

    </div>
</div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

<div class= "row">
    <div class= "col-md-6 offset-md-3">   <!-- Kayıt formumuz artık sayfanın ortasında gözüküyor-->

<h3>Kayıt Ol</h3>
<hr>

    <form method ="post" >
    {% csrf_token %}   <!-- Güvenlik amacıyla djangonun hata vermesini önlemek için -->

    {{form|crispy}}

    <button type = "submit" class="btn btn-danger">Kayıt Ol</button>
    </form>

    </div>
</div>


{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

<div class= "row">
    <div class= "col-md-6 offset-md-3">   <!-- Makale Ekle formumuz artık sayfanın ortasında gözüküyor-->

<h3>Makale Güncelle</h3>
<hr>

    <form method ="post" >
    {% csrf_token %}   <!-- Güvenlik amacıyla djangonun hata vermesini önlemek için -->

    {{form.media}}   <!-- Ckeditörün kullanılabilmesi için -->
    {{form|crispy}}

    <button type = "submit" class="btn btn-danger">Güncelle</button>
    </form>

    </div>
</div>

{% endblock body %}